/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgettoRouteImport } from './routes/progetto'
import { Route as LagunaRouteImport } from './routes/laguna'
import { Route as GardaRouteImport } from './routes/garda'
import { Route as IndexRouteImport } from './routes/index'

const ProgettoRoute = ProgettoRouteImport.update({
  id: '/progetto',
  path: '/progetto',
  getParentRoute: () => rootRouteImport,
} as any)
const LagunaRoute = LagunaRouteImport.update({
  id: '/laguna',
  path: '/laguna',
  getParentRoute: () => rootRouteImport,
} as any)
const GardaRoute = GardaRouteImport.update({
  id: '/garda',
  path: '/garda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/garda': typeof GardaRoute
  '/laguna': typeof LagunaRoute
  '/progetto': typeof ProgettoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/garda': typeof GardaRoute
  '/laguna': typeof LagunaRoute
  '/progetto': typeof ProgettoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/garda': typeof GardaRoute
  '/laguna': typeof LagunaRoute
  '/progetto': typeof ProgettoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/garda' | '/laguna' | '/progetto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/garda' | '/laguna' | '/progetto'
  id: '__root__' | '/' | '/garda' | '/laguna' | '/progetto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GardaRoute: typeof GardaRoute
  LagunaRoute: typeof LagunaRoute
  ProgettoRoute: typeof ProgettoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progetto': {
      id: '/progetto'
      path: '/progetto'
      fullPath: '/progetto'
      preLoaderRoute: typeof ProgettoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laguna': {
      id: '/laguna'
      path: '/laguna'
      fullPath: '/laguna'
      preLoaderRoute: typeof LagunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garda': {
      id: '/garda'
      path: '/garda'
      fullPath: '/garda'
      preLoaderRoute: typeof GardaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GardaRoute: GardaRoute,
  LagunaRoute: LagunaRoute,
  ProgettoRoute: ProgettoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
